use_frameworks!

platform :ios, '11.0'

target 'HLYWebViewJSBridge_Example' do
  pod 'HLYWebViewJSBridge', :path => '../'

  target 'HLYWebViewJSBridge_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
